# Tensorflow Base Template

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf

### SAMPLE DATA

In [2]:
import numpy as np

x, y = np.random.rand(1000, 6), np.random.rand(1000).round().astype(int)
train_idx = np.arange(600)
dev_idx = np.arange(600, 800)
test_idx = np.arange(800, 1000)
x_train, y_train = x[train_idx], y[train_idx]
x_dev, y_dev = x[dev_idx], y[dev_idx]
x_test, y_test = x[test_idx], y[test_idx]
print(x)
print(y)
print(x_train.shape, y_train.shape)
print(x_dev.shape, y_dev.shape)
print(x_test.shape, y_test.shape)

[[0.41484394 0.58127769 0.26956681 0.82177679 0.77153481 0.05644298]
 [0.9010685  0.37340044 0.99750411 0.59540178 0.33086306 0.78468117]
 [0.56634228 0.67038674 0.97418446 0.50580377 0.82545101 0.7521692 ]
 ...
 [0.18476658 0.4412313  0.11075006 0.01115178 0.91249964 0.15170191]
 [0.23666751 0.65484846 0.93425127 0.34542081 0.44801269 0.27121247]
 [0.06864369 0.06964571 0.76704467 0.95410107 0.86387377 0.71665298]]
[0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1
 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0
 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 1 0
 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1
 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1
 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 0
 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 

### MODEL

In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])

### TRAINING

In [4]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_dev, y_dev))

Epoch 1/10
19/19 [==============================] - 1s 38ms/step - loss: 0.7964 - accuracy: 0.4694 - val_loss: 0.6963 - val_accuracy: 0.4950
Epoch 2/10
19/19 [==============================] - 0s 3ms/step - loss: 0.7447 - accuracy: 0.4549 - val_loss: 0.6934 - val_accuracy: 0.4900
Epoch 3/10
19/19 [==============================] - 0s 3ms/step - loss: 0.7386 - accuracy: 0.4817 - val_loss: 0.6930 - val_accuracy: 0.5150
Epoch 4/10
19/19 [==============================] - 0s 3ms/step - loss: 0.7025 - accuracy: 0.5055 - val_loss: 0.6927 - val_accuracy: 0.4700
Epoch 5/10
19/19 [==============================] - 0s 3ms/step - loss: 0.7007 - accuracy: 0.5010 - val_loss: 0.6923 - val_accuracy: 0.4950
Epoch 6/10
19/19 [==============================] - 0s 3ms/step - loss: 0.7022 - accuracy: 0.5092 - val_loss: 0.6920 - val_accuracy: 0.5550
Epoch 7/10
19/19 [==============================] - 0s 3ms/step - loss: 0.6996 - accuracy: 0.4920 - val_loss: 0.6914 - val_accuracy: 0.5550
Epoch 8/10
19/19 [=